# Generated by Django 5.2.1 on 2025-06-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="answer",
            field=models.IntegerField(
                blank=True, help_text="추천된 답변 가격", null=True
            ),
        ),
    ]
