# Generated by Django 5.2.1 on 2025-06-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recommendation_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='id',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='Recommendation_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
